sonar.projectKey=library-refactoring-architecture
sonar.projectName=Library Refactoring Architecture
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=reports/junit/junit.xml
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
